### ISSUE TITLE
file_get_contents(): Read of 8192 bytes failed with errno=21 Is a directory

### ISSUE THREAD

**Issue by Eixix** [imanghafoori1/laravel-microscope#133]
Hi, first of all thanks for you awesome work!

It seems that all namespace-related commands throw this error, namely:

- php artisan check:views
- php artisan check:psr4 {-s|--nofix}
- php artisan check:imports {-s|--nofix}
- php artisan check:dd
- php artisan check:bad_practices
- php artisan check:all

I guess this happens, as there are additional folders in my app folder. Simply put unexpected directories.

Cheers

**Comment by imanghafoori1** [comment]
Please mention your exact version of:
microscope
PHP
laravel
OS

Thanks

**Comment by Eixix** [comment]
Sorry for not mentioning it in the first place:

- PHP: v8.0.3
- Laravel: v8.44
- Microscope: v1.0
- OS: Happens on Windows 10 / KDE Neon (Linux)

Stack trace is:
```
file(): Read of 8192 bytes failed with errno=21 Is a directory

  at vendor/imanghafoori/laravel-microscope/src/Commands/CheckPsr4.php:63
     59▕     }
     60▕ 
     61▕     private function fixRefs($_path, $olds, $news)
     62▕     {
  ➜  63▕         $lines = file($_path);
     64▕         $changed = [];
     65▕         $olds = $this->deriveVariants($olds);
     66▕         $news = $this->deriveVariants($news);
     67▕         foreach ($lines as $i => $line) {

      +27 vendor frames
  28  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by imanghafoori1** [comment]
Do you have a file and folder with the same name side by side?

**Comment by Eixix** [comment]
We have quite a large laravel project so I can't be 100 percent certain, however 90% certain that we dont have the same names side by side in the PHP part of the project (only in the scss and js part).

**Comment by imanghafoori1** [comment]
please try it on the latest version again to see the problem still exists. @Eixix

**Comment by imanghafoori1** [comment]
You may go to vendor folder and change the code to discover the faulty directory.

 at vendor/imanghafoori/laravel-microscope/src/Commands/CheckPsr4.php:63
     59▕     }
     60▕ 
     61▕     private function fixRefs($_path, $olds, $news)
     62▕     {
       ➜           is_dir($_path) && dd($_path); //       <=======             add this
     63▕         $lines = file($_path);
     64▕         $changed = [];
     65▕         $olds = $this->deriveVariants($olds);
     66▕         $news = $this->deriveVariants($news);
     67▕

**Comment by Eixix** [comment]
So the problem still persists with the latest version 1.0.174

The code you provided to discover the faulty directory just logs the root folder of my laravel installation, which is weird...

Many thanks for you efforts!

**Comment by imanghafoori1** [comment]
Nice clue.
Thanks

**Comment by imanghafoori1** [comment]
@Eixix 
could you please send your composer.json file.
specially autoload part of it.

**Comment by Eixix** [comment]
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.0",
        "ext-intl": "*",
        "ext-json": "*",
        "ext-pdo": "*",
        "barryvdh/laravel-dompdf": "^0.9.0",
        "codezero/laravel-unique-translation": "^3.4",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "grkamil/laravel-telegram-logging": "^v1.4.2",
        "guzzlehttp/guzzle": "^7.1.0",
        "laravel/framework": "^8.6",
        "laravel/telescope": "^4.4",
        "laravel/tinker": "^2.4",
        "laravel/ui": "^3.0",
        "maatwebsite/excel": "^3.1",
        "predis/predis": "^1.1",
        "sopamo/laravel-filepond": "^0.6.1",
        "spatie/laravel-backup": "^7.5",
        "spatie/laravel-menu": "^3.6",
        "spatie/laravel-sluggable": "^2.6",
        "spatie/laravel-translatable": "^4.6",
        "spatie/menu": "^2.8",
        "tymon/jwt-auth": "^1.0",
        "league/flysystem-sftp": "~1.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.7",
        "facade/ignition": "^2.3.7",
        "fzaninotto/faker": "^1.9.1",
        "laravel/dusk": "^6.10.0",
        "matt-allan/laravel-code-style": "^0.6.0",
        "mockery/mockery": "^1.4.0",
        "mrclay/shibalike": "^1.0",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "check-style": "php-cs-fixer fix --dry-run --diff",
        "fix-style": "php-cs-fixer fix"
    }
}

```

**Comment by Eixix** [comment]
Sorry sent the wrong one in the first place in case you saw it in the few seconds, now here is the correct one:
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.0",
        "ext-intl": "*",
        "ext-json": "*",
        "ext-pdo": "*",
        "barryvdh/laravel-dompdf": "^0.9.0",
        "codezero/laravel-unique-translation": "^3.4",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "grkamil/laravel-telegram-logging": "^v1.4.2",
        "guzzlehttp/guzzle": "^7.1.0",
        "laravel/framework": "^8.6",
        "laravel/telescope": "^4.4",
        "laravel/tinker": "^2.4",
        "laravel/ui": "^3.0",
        "maatwebsite/excel": "^3.1",
        "predis/predis": "^1.1",
        "sopamo/laravel-filepond": "^0.6.1",
        "spatie/laravel-backup": "^7.5",
        "spatie/laravel-menu": "^3.6",
        "spatie/laravel-sluggable": "^2.6",
        "spatie/laravel-translatable": "^4.6",
        "spatie/menu": "^2.8",
        "tymon/jwt-auth": "^1.0",
        "league/flysystem-sftp": "~1.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.7",
        "facade/ignition": "^2.3.7",
        "fzaninotto/faker": "^1.9.1",
        "imanghafoori/laravel-microscope": "^1.0",
        "laravel/dusk": "^6.10.0",
        "matt-allan/laravel-code-style": "^0.6.0",
        "mockery/mockery": "^1.4.0",
        "mrclay/shibalike": "^1.0",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "check-style": "php-cs-fixer fix --dry-run --diff",
        "fix-style": "php-cs-fixer fix"
    }
}

```

**Comment by imanghafoori1** [comment]
it would be a big help if you open CheckPsr4.php file and comment out these, one by one to see which one is causing the problem.

![image](https://user-images.githubusercontent.com/6961695/122739872-a5980f00-d298-11eb-9d40-81e1ef604f0e.png)

**Comment by Eixix** [comment]
Ah a fellow PHPStorm connaisseur. It is line 93!

**Comment by imanghafoori1** [comment]
to be really sure you may also comment out one of these two loops.

![image](https://user-images.githubusercontent.com/6961695/122743644-68ce1700-d29c-11eb-9d0f-baa37c436d81.png)

**Comment by imanghafoori1** [comment]
I think this file should solve your problem.
I found and solved a few logical problems in it.

Test this please:
[RoutePaths.zip](https://github.com/imanghafoori1/laravel-microscope/files/6686050/RoutePaths.zip)

**Comment by imanghafoori1** [comment]
Please try the dev-master version to see if it works correctly or not.

**Comment by imanghafoori1** [comment]
latest patch should solve the issue.

**Comment by Eixix** [comment]
Is it already released? Because the problem is still there with the dev-master version

**Comment by imanghafoori1** [comment]
yeah, it is released.
At least I think the problem is now from somewhere else.
Please redo the debug steps I just told you, to see if the problem is still from the `RoutePaths::get()`

**Comment by Eixix** [comment]
Ok, even when commenting out every content, the error still persists with the current version (dev-master)

**Comment by imanghafoori1** [comment]
It is strange, is the error exactly the same?

**Comment by imanghafoori1** [comment]
Please comment out one there loops to see which one solves the problem:
.
![image](https://user-images.githubusercontent.com/6961695/123484329-657cb780-d61d-11eb-821f-42230a011250.png)

**Comment by imanghafoori1** [comment]
and remember to check it on the latest commit.

**Comment by Eixix** [comment]
It is the same error message but it does not happen for the check:psr4 but rather the check:imports

**Comment by Eixix** [comment]
The corresponding line that provokes the error is 34 `$this->checkFilePaths(RoutePaths::get())`

**Comment by imanghafoori1** [comment]
I am curious to see what this dd will produce in your app.
I guess you can a `Route::group([...], 'someWrongPath');` in your project.

![image](https://user-images.githubusercontent.com/6961695/124286760-82a50f00-db64-11eb-8c22-a07bedf020ec.png)

**Comment by Eixix** [comment]
It will output this (shortened the absolute paths, it is just my project folder and all path prefixes are the same):

```
Checking imports...
array:4 [
  0 => "/routes/admin.php"
  1 => "/routes/auth.php"
  2 => "/routes/web.php"
  3 => "/routes/api.php"
]
array:4 [
  0 => "/routes/admin.php"
  1 => "/routes/auth.php"
  2 => "/routes/web.php"
  3 => "/routes/api.php"
]
```

**Comment by imanghafoori1** [comment]
What about this??
![image](https://user-images.githubusercontent.com/6961695/124300077-66f53500-db73-11eb-86d1-faaf30f6b483.png)

**Comment by Eixix** [comment]
```
array:5 [
  0 => "/project/routes/admin.php"
  1 => "/project/routes/auth.php"
  2 => "/project/routes/web.php"
  3 => "/project/routes/api.php"
  4 => "/project"
]

```

**Comment by imanghafoori1** [comment]
I think if you change the code this way, it will work.
Also I want to know how you have loaded an extra route file by calling `loadRoutesFrom` method in your service provider.

![image](https://user-images.githubusercontent.com/6961695/124300349-ba678300-db73-11eb-96d6-96de71b73814.png)

**Comment by Eixix** [comment]
Now i think I found another issue, but the initial one is gone 😨
and yes I use this method

```
Checking imports...
"==========================================================="
"was not able to properly parse the: /project/app/Extensions/Auth/Backend/Native/AuthenticatesIdpUsers.php file."
"Please open up an issue on the github repo"
"https://github.com/imanghafoori1/laravel-microscope/issues"
"and also send the content of the file to fix the issue."
"========================== Thanks =========================="

   ErrorException 

  foreach() argument must be of type array|object, null given

  at vendor/imanghafoori/laravel-microscope/src/CheckClassReferencesAreValid.php:176
    172▕ 
    173▕         $printer = app(ErrorPrinter::class);
    174▕ 
    175▕         loopStart:
  ➜ 176▕         foreach ($nonImportedClasses as $nonImportedClass) {
    177▕             $class = $nonImportedClass['class'];
    178▕             $line = $nonImportedClass['line'];
    179▕ 
    180▕             if (! self::isAbsent($class) || \function_exists($class)) {

      +18 vendor frames
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by imanghafoori1** [comment]
The problem is with my code, not your side.
I want to know how you have called the `loadRoutesFrom` what you have passed to it?

**Comment by imanghafoori1** [comment]
also the contents of this file is needed:
/project/app/Extensions/Auth/Backend/Native/AuthenticatesIdpUsers.php

**Comment by Eixix** [comment]
We have our own service provider, where we call this method like this:
```
$path = app_path('Extensions/Shibalike/routes/routes.php');
$this->loadRoutesFrom($path);
```

Here you have the contents of AuthenticatesIdpUsers.php:
```
<?php

namespace App\Extensions\Auth\Backend\Embedded;

use App\Extensions\Auth\Backend\Native\AuthenticatesIdpUsers as NativeAuthenticatesIdpUsers;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Http\Request;

trait AuthenticatesIdpUsers
{
    /*
    |--------------------------------------------------------------------------
    | Authenticates Idp Users Trait
    |--------------------------------------------------------------------------
    |
    | This trait extends the native Authenticates Idp Users Trait with an
    | embedded mode returning authentication tokens. In order to disable
    | embedded usage, just use the native trait instead of this one.
    |
    */

    use NativeAuthenticatesIdpUsers, Concerns\EmbedsAuthentication;

    /**
     * The user has been authenticated.
     *
     * @param Request $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        return $this->succeeded();
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return Guard
     */
    protected function guard()
    {
        return $this->authenticator();
    }
}
```

**Comment by imanghafoori1** [comment]
@Eixix I think this file is not the one causing the error.
it seems you have an other one with the same name in the `Native` folder (not `Embedded` folder).
Microscope has no problem with the one you just sent.

**Comment by Eixix** [comment]
Oh yeah sorry my bad. Here you can find the class:
```php
<?php

namespace App\Extensions\Auth\Backend\Native;

use App\Extensions\Auth\Backend\Native\IdpHandlers\Contracts\Handler;
use Illuminate\Contracts\Auth\StatefulGuard;
use Illuminate\Foundation\Auth\RedirectsUsers;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;
use Illuminate\SUpport\Str;

trait AuthenticatesIdpUsers
{
    use RedirectsUsers;

    /**
     * Send the user away to the Idp for authentication.
     *
     * @param  string  $idp
     * @param  string  $target
     * @return RedirectResponse
     */
    protected function login(string $idp, string $target)
    {
        return $this->handler()->login($idp, $target);
    }

    /**
     * Setup authentication based on returned data from the IdP.
     *
     * @param Request $request
     * @return RedirectResponse|\Illuminate\Http\Response|JsonResponse
     *
     * @throws HttpResponseException
     */
    public function idpAuth(Request $request)
    {
        $data = $this->validateRequest();
        $user = $this->updateOrCreate($data);

        return $this->loginAndRespond($request, $user);
    }

    /**
     * Validate authorization and data of an incoming request of the Idp.
     *
     * @return array
     *
     * @throws HttpResponseException
     */
    protected function validateRequest()
    {
        $data = $this->data();

        if (! $this->isAuthorized()) {
            $this->back(trans('auth.forbidden'));
        }
        if (! $this->isValid($data)) {
            $this->back(trans('auth.invalid'));
        }

        return $data;
    }

    /**
     * Send the response after the user was authenticated and logged in.
     *
     * @param Request $request
     * @param  mixed  $user
     * @return RedirectResponse|\Illuminate\Http\Response
     */
    protected function loginAndRespond(Request $request, $user)
    {
        $this->guard()->login($user);
        $request->session()->regenerate();

        if ($response = $this->authenticated($request, $user)) {
            return $response;
        }

        return $request->wantsJson()
            ? Response::noContent()
            : Redirect::intended($this->redirectPath());
    }

    /**
     * The user has been authenticated.
     *
     * @param Request $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        //
    }

    /**
     * Get all required server variables.
     *
     * @return array
     */
    protected function data()
    {
        $handler = $this->handler();

        foreach ($this->rules() as $key => $rule) {
            $data[$key] = $handler->variable($key);
        }

        return $data ?? [];
    }

    /**
     * Check if the authenticated user has any of the given entitlements.
     *
     * @param  string|array $entitlements
     * @return bool
     */
    protected function isEntitled($entitlements)
    {
        $affiliations = $this->handler()->variable('affiliation');

        return Str::contains($affiliations, $entitlements);
    }

    /**
     * Determine if the data of an incoming authentication request is valid.
     *
     * @param  array  $data
     * @return bool
     */
    protected function isValid(array $data)
    {
        return Validator::make($data, $this->rules())->passes();
    }

    /**
     * Send the user back to the login page and show them a message.
     *
     * @param  string  $message
     * @return void
     *
     * @throws HttpResponseException
     */
    protected function back(string $message)
    {
        abort(Redirect::route('home')->with(['status' => 'info', 'message' => $message]));
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard();
    }

    /**
     * Get the idp handler to be used during authentication.
     *
     * @return Handler
     */
    protected function handler()
    {
        return config('auth.emulate_idp')
            ? new IdpHandlers\Shibalike
            : new IdpHandlers\Shibboleth;
    }
}

```

**Comment by imanghafoori1** [comment]
try out the latest patch and it would be fine for you.

**Comment by Eixix** [comment]
Everything is working now, thanks a lot for your work and effort! :)
